### ISSUE TITLE
Issue with text alignment

### ISSUE THREAD

**Issue by Nyankoo** [jp-netsis/RubyTextMeshPro#9]
I'm experiencing an issue with text alignment / centering, please see below's screenshots:

Here, the text is not aligned / not horizontally centered.
![image](https://github.com/jp-netsis/RubyTextMeshPro/assets/6652214/f99424ac-af8e-4e9b-b27e-b5dbdb2758c0)
![image](https://github.com/jp-netsis/RubyTextMeshPro/assets/6652214/1be0e2f1-4568-4b7d-805e-c1b804b8bebc)

Here, the text is correctly aligned / horizontally centered (same TMP object).
![image](https://github.com/jp-netsis/RubyTextMeshPro/assets/6652214/46ce19d6-b8e7-4dac-91e0-a16e27360e77)
![image](https://github.com/jp-netsis/RubyTextMeshPro/assets/6652214/c3952367-1414-4c0a-a136-5996224aa8fb)

This is in Unity 2021.3.28f1, TMP version 3.0.6 and the latest version of this plugin.

**Comment by jp-netsis** [comment]
Unfortunately, this issue is a known problem with TextMeshPro.
Below is the appearance when using the space tag for center alignment.

<img width="1222" alt="Screenshot 2023-07-31 at 22 21 50" src="https://github.com/jp-netsis/RubyTextMeshPro/assets/36494806/aeeec942-e785-494e-9f6a-95ecb08c3937">

I think this issue is due to aligning with the position of the last character of the described ruby, which was returned using the "space" tag. Therefore, as a temporary measure, excluding the ruby from the last character may help alleviate the problem.

```
<r=　とりかえる>取り替え</r>る
or
<r=とりかえる>取り替える</r><size=0%>a</size>
```

<img width="1220" alt="Screenshot 2023-07-31 at 22 32 38" src="https://github.com/jp-netsis/RubyTextMeshPro/assets/36494806/e3c9bf7a-cb2d-4de3-92fe-02c3e596430a">

**Comment by Nyankoo** [comment]
@jp-netsis Thank you for the detailed explanation! I "fixed" the issue by adding "<size=0.01em>.</size>" after the </r>, which has the same effect as the workaround you described!
